Abort deploy if client build failed
pemberton-rank/react-shopify-app pull request #29
Opened 2018-08-17 12:56 UTC by mib32

https://trello.com/c/vfbpj57F/404-capistrano-break-the-build-if-unable-to-build-the-frontend

2018-08-20 14:36 UTC, Julianobsg requested changes

2018-08-20 14:36 UTC, Julianobsg commented on config/deploy.rb
> +          end
following the caps documentation, you could use something like this:

`if test("[ -f somefile.txt ]")
    execute(:cp, 'somefile.txt', 'somewhere_else.txt')
  end`

I'm concerned about checking the string because if tomorrow some new npm version change the text to could not build the client, this will never break again, and we can have the same problem again.

2018-08-20 15:45 UTC, mib32 commented on config/deploy.rb
> +          end
Hmm... That makes sense. But I don't understand how can I use your example here? I am checking the return message of npm, but what is other options to see if npm successfully built?

2018-08-20 15:51 UTC, Julianobsg commented on config/deploy.rb
> +          end
Is webpack returning status code 0? Could not replicate this error, but if there is no error code to check here, so the problem is not related with Capistrano, right?

2018-08-20 15:53 UTC, Julianobsg commented on config/deploy.rb
> +          end
Is that for the symlink problem?

2018-08-20 15:56 UTC, mib32 commented on config/deploy.rb
> +          end
@Julianobsg I can't check the status code from 'execute' method. How this is done here is the only option I managed to make it.

2018-08-20 15:56 UTC, mib32 commented on config/deploy.rb
> +          end
> Is that for the symlink problem?

No just sometimes the build is not happening okay.

2018-08-30 12:12 UTC, Julianobsg approved these changes

2018-08-31 10:52 UTC, merged